### ISSUE TITLE
Testimonials page

### ISSUE THREAD

**Issue by JessePeplinski** [PotsdamACM/hackpotsdam#5]
Gather from eboard members, and email participants on a quick blurb. From both students & sponsors.

**Comment by lannonbr** [comment]
I could write a short blurb, how short are you wanting for it?

**Comment by JessePeplinski** [comment]
That would be awesome! I figure 3-4 sentences should be fine. Thanks!

**Comment by JessePeplinski** [comment]
This issue was moved to hackpotsdam/hackpotsdam.github.io#30
